#!/bin/sh

CYAN="\033[1;36m"
RED="\033[1;31m"
GREEN="\033[1;32m"
NC="\033[0m"

linter_exit_code=1

staged_ts_files=$(git diff --cached --diff-filter=d --name-only | grep .ts$);

if [ -z "$staged_ts_files" ]
then
  echo "${CYAN}no staged typescript files${NC}"
  exit 0
fi

echo "${CYAN}linting staged typescript files${NC}"
npx eslint --fix --color $staged_ts_files
linter_exit_code=$?

if [ $linter_exit_code -ne 0 ]
then
  echo "${RED} ❌ Linter errors have occurred ( ͡ಥ ͜ʖ ͡ಥ)${NC}"
  exit 1
else
  echo "${GREEN} ✔ eslint did not find any errors [̲̅$̲̅(̲̅ ͡° ͜ʖ ͡°̲̅)̲̅$̲̅]${NC}"
  echo "${CYAN} running prettier"
  npx prettier --write $staged_ts_files
  exit 0
fi
